import { WatchlistRecord } from "./WatchlistProvider";

export const mockWatchlist: WatchlistRecord = {
    60625: {
        id: 60625,
        item: {
            id: 60625,
            title: "Rick and Morty",
            original_title: "Rick and Morty",
            poster: "/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg",
            backdrop: "/eV3XnUul4UfIivz3kxgeIozeo50.jpg",
            vote: 8.8,
            text: "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
            url: "/tv/rick%20and%20morty-60625",
            genres: [
                {
                    id: "16",
                    name: "Animation",
                    media_type: "tv",
                },
                {
                    id: "35",
                    name: "Comedy",
                    media_type: "tv",
                },
                {
                    id: "10765",
                    name: "Sci-Fi & Fantasy",
                    media_type: "tv",
                },
                {
                    id: "10759",
                    name: "Action & Adventure",
                    media_type: "tv",
                },
            ],
            infos: ["Animation, Comedy, Sci-Fi & Fantasy, Action & Adventure"],
            media_type: "tv",
            seasons: [
                {
                    air_date: "2016-10-26",
                    episode_count: 21,
                    id: 106178,
                    name: "Specials",
                    overview: "",
                    poster_path: null,
                    season_number: 0,
                },
                {
                    air_date: "2013-12-02",
                    episode_count: 11,
                    id: 60059,
                    name: "Season 1",
                    overview:
                        "Rick and Morty visit a pawn shop in space, encounter various alternate and virtual realities, and meet the devil at his antique shop.",
                    poster_path: "/pZoqbuJGaVM7vgzsSCPwRH5TCx5.jpg",
                    season_number: 1,
                },
                {
                    air_date: "2015-07-26",
                    episode_count: 10,
                    id: 66738,
                    name: "Season 2",
                    overview:
                        "After Rick and Morty decided to unfreeze time, they must deal with alien parasites, alternate Jerrys and a decaying, possibly non-existent dimension.",
                    poster_path: "/zkhGdE29umuKwa6u6mm7e4cXvYY.jpg",
                    season_number: 2,
                },
                {
                    air_date: "2017-04-01",
                    episode_count: 10,
                    id: 86926,
                    name: "Season 3",
                    overview:
                        "Rick and Morty travel to Atlantis and take some time to relax, plus Rick turns himself into a pickle and faces off against the president.",
                    poster_path: "/lVcwMfbHx4QguLbZT4bink9mcgd.jpg",
                    season_number: 3,
                },
                {
                    air_date: "2019-11-10",
                    episode_count: 10,
                    id: 128112,
                    name: "Season 4",
                    overview: "",
                    poster_path: "/ylL3eViYKBhtjaqVe4pLMslVBjR.jpg",
                    season_number: 4,
                },
                {
                    air_date: "2021-06-20",
                    episode_count: 10,
                    id: 188470,
                    name: "Season 5",
                    overview: "",
                    poster_path: "/wwNZjZuBZy2oF5ovPiwAzNOmO3l.jpg",
                    season_number: 5,
                },
            ],
        },
        bookmark: false,
        progress: 409.151137,
    },
    82856: {
        id: 82856,
        item: {
            id: 82856,
            title: "The Mandalorian",
            original_title: "The Mandalorian",
            poster: "/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
            backdrop: "/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
            text: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
            url: "/tv/the%20mandalorian-82856",
            genres: [
                {
                    id: "10765",
                    name: "Sci-Fi & Fantasy",
                    media_type: "tv",
                },
                {
                    id: "10759",
                    name: "Action & Adventure",
                    media_type: "tv",
                },
                {
                    id: "37",
                    name: "Western",
                    media_type: "tv",
                },
                {
                    id: "18",
                    name: "Drama",
                    media_type: "tv",
                },
            ],
            infos: ["Sci-Fi & Fantasy, Action & Adventure, Western, Drama"],
            media_type: "tv",
            vote: 8.5,
            seasons: [
                {
                    air_date: "2019-11-12",
                    episode_count: 8,
                    id: 110346,
                    name: "Season 1",
                    overview:
                        "Set after the fall of the Empire and before the emergence of the First Order. We follow the travails of a lone gunfighter in the outer reaches of the galaxy far from the authority of the New Republic.",
                    poster_path: "/sUTqIb82LxYhPT0SfI8AR03GLpz.jpg",
                    season_number: 1,
                },
                {
                    air_date: "2020-10-30",
                    episode_count: 8,
                    id: 153254,
                    name: "Season 2",
                    overview:
                        "The Mandalorian and the Child continue their journey, facing enemies and rallying allies as they make their way through a dangerous galaxy in the tumultuous era after the collapse of the Galactic Empire.",
                    poster_path: "/b8cs9DzhxRQLQ7TvfLihYbAC6fg.jpg",
                    season_number: 2,
                },
            ],
        },
        progress: 0,
        bookmark: true,
    },
    94305: {
        id: 94305,
        item: {
            id: 94305,
            title: "The Walking Dead: World Beyond",
            original_title: "The Walking Dead: World Beyond",
            poster: "/z31GxpVgDsFAF4paZR8PRsiP16D.jpg",
            backdrop: "/pLVrN9B750ehwTFdQ6n3HRUERLd.jpg",
            text: "A heroic group of teens sheltered from the dangers of the post-apocalyptic world receive a message that inspires them to leave the safety of the only home they have ever known and embark on a cross-country journey to find the one man who can possibly save the world.",
            url: "/tv/the%20walking%20dead%3A%20world%20beyond-94305",
            genres: [
                {
                    id: "18",
                    name: "Drama",
                    media_type: "tv",
                },
                {
                    id: "10765",
                    name: "Sci-Fi & Fantasy",
                    media_type: "tv",
                },
                {
                    id: "9648",
                    name: "Mystery",
                    media_type: "tv",
                },
            ],
            infos: ["Drama, Sci-Fi & Fantasy, Mystery"],
            media_type: "tv",
            vote: 7.7,
            seasons: [
                {
                    air_date: "2020-10-04",
                    episode_count: 10,
                    id: 133610,
                    name: "Season 1",
                    overview: "",
                    poster_path: "/z31GxpVgDsFAF4paZR8PRsiP16D.jpg",
                    season_number: 1,
                },
            ],
        },
        progress: 693.533222,
        bookmark: false,
    },
    495764: {
        id: 495764,
        item: {
            id: 495764,
            title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
            original_title: "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
            poster: "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
            backdrop: "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
            text: "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
            url: "/movie/birds%20of%20prey%20(and%20the%20fantabulous%20emancipation%20of%20one%20harley%20quinn)-495764",
            genres: [
                {
                    id: "28",
                    name: "Action",
                    media_type: "movie",
                },
                {
                    id: "80",
                    name: "Crime",
                    media_type: "movie",
                },
            ],
            infos: ["5. February 2020", "109 min", "Action, Crime"],
            vote: 7.1,
            media_type: "movie",
        },
        bookmark: false,
        progress: 731.348013,
    },
    544401: {
        id: 544401,
        item: {
            id: 544401,
            title: "Cherry",
            original_title: "Cherry",
            poster: "/pwDvkDyaHEU9V7cApQhbcSJMG1w.jpg",
            backdrop: "/uQtqiAu2bBlokqjlURVLEha6zoi.jpg",
            text: "Cherry drifts from college dropout to army medic in Iraq - anchored only by his true love, Emily. But after returning from the war with PTSD, his life spirals into drugs and crime as he struggles to find his place in the world.",
            url: "/movie/cherry-544401",
            genres: [
                {
                    id: "80",
                    name: "Crime",
                    media_type: "movie",
                },
                {
                    id: "18",
                    name: "Drama",
                    media_type: "movie",
                },
            ],
            infos: ["26. February 2021", "140 min", "Crime, Drama"],
            vote: 7.5,
            media_type: "movie",
        },
        bookmark: true,
        progress: 0,
    },
    615457: {
        id: 615457,
        item: {
            id: 615457,
            title: "Nobody",
            original_title: "Nobody",
            poster: "/oBgWY00bEFeZ9N25wWVyuQddbAo.jpg",
            backdrop: "/6zbKgwgaaCyyBXE4Sun4oWQfQmi.jpg",
            text: 'Hutch Mansell, a suburban dad, overlooked husband, nothing neighbor — a "nobody." When two thieves break into his home one night, Hutch\'s unknown long-simmering rage is ignited and propels him on a brutal path that will uncover dark secrets he fought to leave behind.',
            url: "/movie/nobody-615457",
            genres: [
                {
                    id: "28",
                    name: "Action",
                    media_type: "movie",
                },
                {
                    id: "80",
                    name: "Crime",
                    media_type: "movie",
                },
                {
                    id: "18",
                    name: "Drama",
                    media_type: "movie",
                },
            ],
            infos: ["26. March 2021", "92 min", "Action, Crime, Drama"],
            vote: 8.4,
            media_type: "movie",
        },
        bookmark: false,
        progress: 264.840811,
    },
    634528: {
        id: 634528,
        item: {
            id: 634528,
            title: "The Marksman",
            original_title: "The Marksman",
            poster: "/6vcDalR50RWa309vBH1NLmG2rjQ.jpg",
            backdrop: "/5Zv5KmgZzdIvXz2KC3n0MyecSNL.jpg",
            text: "Jim Hanson’s quiet life is suddenly disturbed by two people crossing the US/Mexico border – a woman and her young son – desperate to flee a Mexican cartel. After a shootout leaves the mother dead, Jim becomes the boy’s reluctant defender. He embraces his role as Miguel’s protector and will stop at nothing to get him to safety, as they go on the run from the relentless assassins.\r Stars...Liam Neeson",
            url: "/movie/the%20marksman-634528",
            genres: [
                {
                    id: "28",
                    name: "Action",
                    media_type: "movie",
                },
                {
                    id: "53",
                    name: "Thriller",
                    media_type: "movie",
                },
                {
                    id: "80",
                    name: "Crime",
                    media_type: "movie",
                },
            ],
            infos: ["15. January 2021", "108 min", "Action, Thriller, Crime"],
            vote: 7.3,
            media_type: "movie",
        },
        progress: 0,
        bookmark: true,
    },
    791373: {
        id: 791373,
        item: {
            id: 791373,
            title: "Zack Snyder's Justice League",
            original_title: "Zack Snyder's Justice League",
            poster: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
            backdrop: "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
            text: "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
            url: "/movie/zack%20snyder's%20justice%20league-791373",
            genres: [
                {
                    id: "28",
                    name: "Action",
                    media_type: "movie",
                },
                {
                    id: "12",
                    name: "Adventure",
                    media_type: "movie",
                },
                {
                    id: "14",
                    name: "Fantasy",
                    media_type: "movie",
                },
                {
                    id: "878",
                    name: "Science Fiction",
                    media_type: "movie",
                },
            ],
            infos: ["18. March 2021", "242 min", "Action, Adventure, Fantasy, Science Fiction"],
            vote: 8.4,
            media_type: "movie",
        },
        bookmark: false,
        progress: 317.613282,
    },
};
